# Generated by Django 4.0.6 on 2022-07-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('nickname', models.CharField(default='', max_length=32, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=16, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
